
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.39.48:3306/manage?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: yj@20200630!YJ
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

## 开启Swagger的Basic认证功能,默认是false
knife4j:
  basic:
    enable: true
    ## Basic认证用户名
    username: foresight
    ## Basic认证密码
    password: foresight
server:
  port: 8080
