spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.39.48:3306/manage?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yj@20200630!YJ
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
    time-zone: GMT+8


  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

## 开启Swagger的Basic认证功能,默认是false
knife4j:
  basic:
    enable: true
    ## Basic认证用户名
    username: foresight
    ## Basic认证密码
    password: foresight
server:
  port: 8080

logging:
  file:
    name: /data/log/foresight.log
    # 超过50M归档文件
    max-size: 50MB
  level:
    com.zhs.backmanageb.mapper: debug
    org.springframework: warn
    org.apache.ibatis.logging: debug

